[tool.poetry]
package-mode = false
name = "homework-05"
version = "0.1.0"
description = ""
authors = ["Dgonede <dgonegonee@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"



